local highlight = require "nacro.utils.highlight"

return function()
  vim.api.nvim_set_hl(0, "Visual", { bg = "#3b4252" })
  vim.api.nvim_set_hl(0, "IncSearch", { link = "Visual" })
  vim.api.nvim_set_hl(0, "Search", { link = "Visual" })
  vim.api.nvim_set_hl(0, "Substitute", { link = "Visual" })
  vim.api.nvim_set_hl(0, "DiffAdd", { bold = false })
  vim.api.nvim_set_hl(0, "DiffChange", { bold = false })
  vim.api.nvim_set_hl(0, "DiffText", { bold = false })
  vim.api.nvim_set_hl(0, "CursorLine", { bg = "#20252d" })
  vim.api.nvim_set_hl(0, "Function", { bg = "NONE" })

  vim.api.nvim_set_hl(0, "Pmenu", { bg = "#1f242d" })
  vim.api.nvim_set_hl(0, "PmenuSel", { link = "Visual" })
  vim.api.nvim_set_hl(0, "PmenuThumb", { link = "Visual" })
  vim.api.nvim_set_hl(0, "PmenuSbar", { link = "Pmenu" })
  vim.api.nvim_set_hl(0, "StatusLine", { bg = "#1f242d" })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { bold = true })

  vim.api.nvim_set_hl(0, "DapUIModifiedValue", { link = "Visual" })
  vim.api.nvim_set_hl(0, "DapExecutionLine", { bg = "#384752" })
  vim.api.nvim_set_hl(0, "DapBreakpointLine", { bg = "#43343e" })
  vim.api.nvim_set_hl(0, "DapUIDecoration", { link = "NvimTreeFolderIcon" })
  vim.api.nvim_set_hl(0, "DapUIScope", { link = "Title" })
  vim.api.nvim_set_hl(0, "DapUIVariable", { link = "Keyword" })
  vim.api.nvim_set_hl(0, "DapUISource", { link = "Special" })
  vim.api.nvim_set_hl(0, "DapUIValue", { link = "Normal" })
  vim.api.nvim_set_hl(0, "DapUILineNumber", { link = "Number" })
  vim.api.nvim_set_hl(0, "DapUIStoppedThread", { link = "Function" })
  vim.api.nvim_set_hl(0, "DapUIThread", { link = "Tag" })
  vim.api.nvim_set_hl(0, "DapUIDecoration", { link = "NvimTreeFolderIcon" })

  vim.api.nvim_set_hl(0, "TelescopeSelection", { link = "Visual" })
  vim.api.nvim_set_hl(0, "TelescopeMultiSelection", { link = "Visual" })
  vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = "#1f242d" })
  vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { link = "TelescopeNormal" })
  vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { link = "TelescopeNormal" })
  vim.api.nvim_set_hl(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
  vim.api.nvim_set_hl(0, "TelescopeBorder", { link = "TelescopeNormal" })
  vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { link = "TelescopeBorder" })
  vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { link = "TelescopeBorder" })
  vim.api.nvim_set_hl(0, "TelescopePromptBorder", { link = "TelescopeBorder" })
  vim.api.nvim_set_hl(0, "TelescopePreviewTitle", { link = "NonText" })

  vim.api.nvim_set_hl(0, "NeogitRemote", { link = "Number" })
  vim.api.nvim_set_hl(0, "NeogitObjectId", { link = "NonText" })
  vim.api.nvim_set_hl(0, "NeogitTagName", { link = "Special" })
  vim.api.nvim_set_hl(0, "NeogitRecentCommits", { link = "Title" })
  vim.api.nvim_set_hl(0, "NeogitUnstagedchanges", { link = "Title" })
  vim.api.nvim_set_hl(0, "NeogitBranch", { link = "Directory" })

  vim.api.nvim_set_hl(0, "NavicIconsProperty", { link = "Field" })
  vim.api.nvim_set_hl(0, "NavicIconsClass", { link = "Type" })
  vim.api.nvim_set_hl(0, "NavicIconsMethod", { link = "Function" })
  vim.api.nvim_set_hl(0, "NavicIconsFunction", { link = "Function" })
  vim.api.nvim_set_hl(0, "NavicIconsConstant", { link = "Constant" })
  vim.api.nvim_set_hl(0, "NavicIconsInterface", { link = "Keyword" })
end
