local highlight = require "nacro.utils.highlight"

return function()
  highlight("Visual", { guibg = "#3b4252" })
  highlight("IncSearch", "Visual")
  highlight("Search", "Visual")
  highlight("Substitute", "Visual")
  highlight("DiffAdd", { gui = "NONE" })
  highlight("DiffChange", { gui = "NONE" })
  highlight("DiffText", { gui = "NONE" })
  highlight("CursorLine", { guibg = "#20252d" })
  highlight("Function", { guibg = "NONE" })

  highlight("DapUIModifiedValue", "Visual")
  highlight("DapExecutionLine", { guibg = "#384752" })
  highlight("DapBreakpointLine", { guibg = "#43343e" })
  highlight("DapUIDecoration", "NvimTreeFolderIcon")
  highlight("DapUIScope", "Title")
  highlight("DapUIVariable", "Keyword")
  highlight("DapUISource ", "Special")
  highlight("DapUIValue", "Normal")
  highlight("DapUILineNumber", "Number")
  highlight("DapUIStoppedThread", "Function")
  highlight("DapUIThread", "Tag")
  highlight("DapUIDecoration", "NvimTreeFolderIcon")

  highlight("TelescopeSelection", "Visual")
  highlight("TelescopeMultiSelection", "Visual")

  highlight("NeogitRemote", "Number")
  highlight("NeogitObjectId", "NonText")
  highlight("NeogitTagName", "Special")
  highlight("NeogitRecentCommits", "Title")
  highlight("NeogitUnstagedchanges", "Title")
  highlight("NeogitBranch", "Directory")

  highlight("NavicIconsProperty", "Field")
  highlight("NavicIconsClass", "Type")
  highlight("NavicIconsMethod", "Function")
  highlight("NavicIconsFunction", "Function")
  highlight("NavicIconsConstant", "Constant")
end
